# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiseaseDict' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DiseaseDict
#  pod 'LIHImageSlider'
  pod 'ImageSlideshow', '~> 1.9.0'
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 5.15.7'
  pod 'SoftUIView'
  pod 'RealmSwift'
  pod 'ScrollableSegmentedControl', '~> 1.5.0'
  pod 'Schedule', '~> 2.0'
  pod 'Google-Mobile-Ads-SDK'
  
  target 'DiseaseDictTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DiseaseDictUITests' do
    # Pods for testing
  end

end
